### ISSUE TITLE
Sample App GSDML

### ISSUE THREAD

**Issue by svenhaitjema** [rtlabs-com/p-net#1]
Dear Hans-Erik,

Would it be possible to upload a sample GSDML file that matches the code in the sample_app directory? 

Kind regards,

Sven-Erik

**Comment by nakarlsson** [comment]
I'm working on it

**Comment by svenhaitjema** [comment]
Thank you very much! I can setup a test with TIA 15 and S7-1200 PLC. Please let me know if you need any feedback from that test :)

**Comment by jstavats** [comment]
Hi,

Any chance you could give a quick description of what is needed to be done to use this sample?  I've updated the IP address and the ethernet device (eth0) to match my machine, but the PLC is giving a "Module configured but not available (inserted and configured module types are not the same) - Expected type: IO Device (12345) - Current Type: Not Available".   The sample looks to be setting the iodevice to 12345.

Thanks,
Jay

**Comment by svenhaitjema** [comment]
Dear Jstavats, 

There is a known issue with the library + GSDML file when used with Siemens TIA. Could you specify what your setup is? ( So PLC brand/type, and software studio version? )

Please see the conversation in this pull request, maybe it relates to the error you are observing.

Kind regards,

**Comment by jstavats** [comment]
Hi, 

My current test setup is older, the PLC is Siemens CPU315-2 PN/DP and Software is SIMATIC STEP 7 Professional 2010 v5.5 +SP3. 

Jay
