### ISSUE TITLE
IN Cent OS The application is not running

### ISSUE THREAD

**Issue by Rayapati1203** [rtlabs-com/p-net#109]
Hi 
Earlier i  have posted one issue reference -  #73 
Environment :
I am running this app in CentOS7.7 on Virtual box environment. The image i selected as minimal for CentOS.
CentOS:
static address static ip address to 192.168.0.13,255.255.255.0,gateway - 192.168.0.1,inetrface: enp0s3, Bridge adapter
PLC(RASPberry Pi) : static ip address to 192.168.0.10,255.255.255.0,gateway - 192.168.0.1,inetrface: eth0,
HOST OS (win10) : static ip address to 192.168.0.11,255.255.255.0,gateway - 192.168.0.1

IO Modules configuration 
![IO module configuration](https://user-images.githubusercontent.com/55705864/84242186-145b5d80-aac6-11ea-982d-ae4516c0cc46.png)

Now i took the correct script and run the App in centos - i did not get any error wit this script.
snap shot
![App_running_on_censtOS7 7](https://user-images.githubusercontent.com/55705864/84241913-c0e90f80-aac5-11ea-934b-13b806549978.png)

Reference Snap shot - codesys IDE with wrieshark image capture
Error Status of the device: 16C9A049(Host Unreachable_in_device Status)
The device is identified with correct IP and proper station name.  But for sore reason the ARP is not reachable to device(captured the wireshark traffic) . The connection response is not going back to PLC controller from device.
![Host Unreachable_in_device Status](https://user-images.githubusercontent.com/55705864/84242553-9a77a400-aac6-11ea-8e47-1eddc998e6bc.png)

Do you have any inputs on this scenario, that will be helpful for me. 
I am able to run the application in Ubuntu environment without any issue.

Regards
Rayapati

**Comment by nakarlsson** [comment]
Hi @Rayapati1203, can you share your VBox CentOS image?

**Comment by Rayapati1203** [comment]
HI 
Can you please provide the Google drive link as you mentioned in the mail.

Regards
Rayapati

**Comment by nakarlsson** [comment]
Firewall issue, open ports as described in this link worked. Only open ports to -0xC0FF is not 100% sure, we’ve seen Profinet controllers using port 60000.



https://product-help.schneider-electric.com/Machine%20Expert/V1.1/en/core_ProfinetIO_Configuration_Editor/topics/_pnio_firewall_packagefilter.htm
