### ISSUE TITLE
Invalid packet length after LLDP packet

### ISSUE THREAD

**Issue by JanVasina** [rtlabs-com/p-net#144]
**Linux:**
When a LLDP or foreign packet is received, it is not handled by `pf_eth_recv()` function (returning 0), which means its buffer is reused in the `os_eth_task()` function.
But the buffer length is preserved in the `len` variable and the subsequent socket `recv()` takes only that number of bytes.
If the LLDP packet is shorter then the next DCP packet, wrong number of data is received.

In the function `os_eth_task()` should be:

`    readlen = recv(eth_handle->socket, p->payload, OS_BUF_MAX_SIZE, 0);
`

instead of 

 `     readlen = recv(eth_handle->socket, p->payload, p->len, 0);
`

file osal/linux/osal_eth.c, line 47.

**Comment by pyhys** [comment]
Thanks for your bug report!

Please review #148
