### ISSUE TITLE
any plan for MRP function?

### ISSUE THREAD

**Issue by frankgp** [rtlabs-com/p-net#197]
For Profinet-IO. the MRP is normally function and it is basic requirements.

**Comment by pyhys** [comment]
Hi, thanks for your input!
We need to finish conformance class B before this.

**Comment by jeppefrandsen** [comment]
+1

**Comment by pyhys** [comment]
Closing as this is a duplicate of #575

**Comment by lin-jingjie** [comment]
When will MRP be realized?  thanks！
