### ISSUE TITLE
Input or Output only slots

### ISSUE THREAD

**Issue by yannickasselin** [rtlabs-com/p-net#22]
Hello,
Using the sample app, I was able to succesfully test Profinet communication with Codesys as a Profinet Master. I was also able to use different slots for communication by modifying the GSDML file and the main_linux.c file

Here's what I get in Codesys. "8 bits IN 8 bits Out" in slot 3 working fine:
![image](https://user-images.githubusercontent.com/9681241/74735340-7b56bd00-521e-11ea-9317-7d4c0ff08d4f.png)

But when I try to add "8 bits IN" in slot 1, I get this error when the PLC connects to the Profinet Stack:  "[ERROR] CMDEV(1604): api 0 exp slot 1 subslot 1 and dir 2 not found"

Here's what I changed in main_linux.c:
![image](https://user-images.githubusercontent.com/9681241/74735840-8100d280-521f-11ea-8c98-6aefa87ffad6.png)
![image](https://user-images.githubusercontent.com/9681241/74735925-aab9f980-521f-11ea-9c15-5f10a9781faf.png)

And here's what I changed in GSDML file:
![image](https://user-images.githubusercontent.com/9681241/74736153-1ef49d00-5220-11ea-84c7-ad4dd2acb4c9.png)
![image](https://user-images.githubusercontent.com/9681241/74736224-3df32f00-5220-11ea-8fca-1e4a88837bfa.png)

I must be missing something?

Same problem if I try to add "8 bits OUT" in slot 2. I get this error:
 "[ERROR] CMDEV(1604): api 0 exp slot 2 subslot 1 and dir 1 not found"

What am I doing wrong?

**Comment by pyhys** [comment]
We have managed to reproduce, and will look into it.

**Comment by pyhys** [comment]
See pull request #36
