### ISSUE TITLE
Public header file should include needed header files

### ISSUE THREAD

**Issue by fredrikdanielmoller** [rtlabs-com/p-net#224]
Currently, an application needs to first #include the file options.h before pnet_api.h can be #included:
```
#include "options.h"
#include <pnet_api.h>
```

Preferably, an application should only need to #include pnet_api.h:
```
#include <pnet_api.h>
```
options.h (renamed pnet_options.h, and put in public include directory) should be #included directly from pnet_api.h.
If some stuff in pnet_options.h does not need to be made public, it can be moved to a private header file.

**Comment by pyhys** [comment]
Maybe also the defines in version.h should be available when including pnet_api.h
