### ISSUE TITLE
Remove private types from public header file

### ISSUE THREAD

**Issue by fredrikdanielmoller** [rtlabs-com/p-net#243]
Currently, there are several types defined in `pnet_api.h` which are not actually used by any public API function. Examples: `pnet_lldp_peer_info_t` and `pf_lldp_chassis_id_t`.

Move those to a private header file, such as `pf_types.h`, as to minimise the API surface.

**Comment by pyhys** [comment]
- pnet_lldp_peer_info_t
- pf_lldp_chassis_id_t
- pnet_im_nvm_t
- pnet_lldp_peer_to_peer_boundary_t
- pnet_lldp_boundary_t
- PNET_DIAG_CH_XXX constants and macros

Anything else?

**Comment by fredrikdanielmoller** [comment]
* PNET_FILENAME_*
* pnet_profibus_delay_t
* pnet_ieee_macphy_t
