### ISSUE TITLE
Why do I need "RecordDataList" for a slot to work?

### ISSUE THREAD

**Issue by yannickasselin** [rtlabs-com/p-net#27]
Hello,
When using the sample_app with the supplied GSDML file, I can see the connection working fine with Codesys:
![image](https://user-images.githubusercontent.com/9681241/74956475-278dd480-53d4-11ea-8619-04794733d5ba.png)

But if I comment out the "RecordDataList" part in the GSDML file like this, communication does not work anymore.
![image](https://user-images.githubusercontent.com/9681241/74956684-789dc880-53d4-11ea-943d-9449d652a671.png)
![image](https://user-images.githubusercontent.com/9681241/74956948-d9c59c00-53d4-11ea-82b4-3c2544c8ceef.png)
And I get this error:
ABORT err_cls 253  err_code 18

What else do I need to do to make it work without the "RecordDataList"?

I am trying to have multiple slots. A couple of "Input Only" slots and a couple of "Output Only" slots.
I think this should be a simple task but I am struggling.

I figured how to increase the PNET_MAX_MODULES in order to have more slots but now I need to figure out how to get more bytes IN/OUT per slots and get rid of the "RecordDataList".

Thank you

**Comment by pyhys** [comment]
Hi, and thanks for your feedback.
After pull request #36 this should be functioning.

**Comment by pyhys** [comment]
Hi, i can now confirm that it is functioning. I removed the RecordDataList part from GSDML-V2.35-rt-labs-IODevice-20200316.xml and tried it with the current version of the Linux sample app.
