### ISSUE TITLE
Profinet resources

### ISSUE THREAD

**Issue by JoeyR** [rtlabs-com/p-net#279]
Hello,

I am looking at integrating a couple of devices that support profinet and I'm wondering if you could point me in the right direction. 

1. Do you have any go-to white papers that lay out the profinet protocol?
2. If I have a device's GSDML, what info from that is needed to communicate with the device? (or is it parsed when you open the connection?). 

Thank you for your time,
JoeyR

**Comment by pyhys** [comment]
Hi Joey!

The Profinet specification is found here: https://www.profibus.com/download/profinet-specification
It is located behind a paywall. I do not know about any open resources describing the protocol details.

The GSDML file is used by the engineering tool (PC program) that is used for programming the PLC. In the file there is information on which modules can be used, and how the cyclic data for each module is laid out. It also contains flags specifying if the advanced or the legacy startup mode should be used etc.

Best regards
Jonas
