### ISSUE TITLE
Error when transferring high amount of data

### ISSUE THREAD

**Issue by Svenson12** [rtlabs-com/p-net#33]
With Profinet up to 1440 bytes of data can be transferred.
But due to an invalid data type of buffer_length in struct pf_ppm_t, this size cannot be achieved.
When the Ethernet packet to be transferred becomes bigger than ~255 byte, the code fails and just a fragment of the packet is transferred.
The data type of this variable should be changed from uint8_t to uint16_t.
https://github.com/rtlabs-com/p-net/blob/95a267c8a2cfde872c24949cb09ab11ba622a3d8/src/pf_types.h#L1116
Can you confirm?

**Comment by pyhys** [comment]
See pull request #35

**Comment by pyhys** [comment]
Thanks for the detailed bug report! Now fixed.
