### ISSUE TITLE
pf_types.h uses protected MSVC keyword

### ISSUE THREAD

**Issue by illishar** [rtlabs-com/p-net#335]
The new addition to pf_types.h doesn't compile in Microsoft compilers:

```
   /* Interface data
    *
    * Interface and ports runtime data.
    */
   struct
   {
      pf_lldp_name_of_device_mode_t name_of_device_mode;
      pf_port_t port[PNET_MAX_PORT];
   } interface;
```

The keyword 'interface' is a global define, in Microsoft compilers. Could it perhaps be renamed to something else? eth_interface?

**Comment by pyhys** [comment]
Great, thanks!
We will fix this.
/Jonas
