### ISSUE TITLE
Codesys doesn't recognize my raspberry Pi

### ISSUE THREAD

**Issue by Gaetanos-99** [rtlabs-com/p-net#392]
Hi hi,

i'm currently setting an IO-Device (Raspberry Pi) and a IO-Controller (Windows Laptop). I connected the my Raspi through a USB Serial Cable to my Laptop. I did everything in the tutorial (GSDML file uploaded in codeSys, uart on my Raspi enabled, etc.). But I have the 2 following issues:
* First issue: I can find my Rapi in codesys:
<img width="449" alt="Screenshot (1)" src="https://user-images.githubusercontent.com/81623053/112982166-7328bb00-915c-11eb-8c9e-9e79bf7c6f12.png">

But when I choose the network interface, there is the ethernet interface eth0, which has everything setted as 0:
<img width="579" alt="Screenshot (2)" src="https://user-images.githubusercontent.com/81623053/112982538-e5010480-915c-11eb-8b06-6ada81c1ce13.png">

* As soon as I call the command "sudo ifconfig eth0 192.168.0.50 netmask 255.255.255.0 up" in order to set my ethernet interface or as soon as I run the command "./pn_dev -v", my Raspi doesn't appear in codesys (Device -> Search Network) anymore.

Can someone please help me? I am quite new in programming Profinet. Thank you in advance

**Comment by pyhys** [comment]
Hi!
You need two Raspberry Pi:s. One running as an IO-device and one running as an IO-controller. Your Windows laptop is used to make changes to the IO-controller settings, but it does not act as an IO-controlller.

Best regards
Jonas

**Comment by Gaetanos-99** [comment]
Thank you very much for your reply! Is there a way to use my laptop as IO-Controller so that the stack would still function?

Best regards
Gaetan

**Comment by pyhys** [comment]
Hi again!
The only IO-controller variants that I know of are a physical PLC (like Siemens) or running the Codesys software on a Raspberry Pi, unfortunately.

Best regards
Jonas

**Comment by Gaetanos-99** [comment]
Hi,
thank you very much for your comment! I'll now close it.

**Comment by Ap040** [comment]
Hello,
I want to know the same thing.
If we test the sample application, can we do it with two PCs?. Like one PC has run the CODESYS PN-master and the other has run our sample application. Both PCs should have connected with an Ethernet cable.

Can this scenario works?.

**Comment by pyhys** [comment]
Best @Ap040!
Not to my knowledge, unfortunately not.

Best regards
Jonas

**Comment by Gaetanos-99** [comment]
Hi again!
Now I am using two raspberry Pis but I still have the same issue. On my Raspberry Pi as an IO Controller the eth0 is still 0. Can you please help me?

Best regards
Gaetan

**Comment by Gaetanos-99** [comment]
https://github.com/rtlabs-com/p-net/issues/416
