### ISSUE TITLE
Network interface et0 doesn't receive any packets

### ISSUE THREAD

**Issue by Gaetanos-99** [rtlabs-com/p-net#416]
Hi hi,
first of all, thank you for providing such a wonderful stack! It is extremely useful.
I followed everything on this tutorial. But I bump on the following problem: The network interface eth0 of my raspberry pi (as an IO Controller) isn't configured in the Codesys Software. Everything is 0 when I choose eth0 as network configuration.
<img width="768" alt="Screenshot (5)" src="https://user-images.githubusercontent.com/81623053/116241200-ee35bf00-a764-11eb-8151-19c21b73a17e.png">

I already included in "/etc/dhcpcd.conf" the lines: "interface eth0" and "static ip_address=192.168.0.100/24". Can someone please help me? I'm really stuck with this...

**Comment by pyhys** [comment]
Hi!
You can run the command `ifconfig` on your Raspberry Pi to show the settings of the network interfaces. Please provide the output.

If you have problems getting Codesys up an running, there is lots of info at https://forge.codesys.com/forge/talk/

Best regards
Jonas

**Comment by Gaetanos-99** [comment]
Hi Jonas,
thank you for your reply. Here is the output:
![image](https://user-images.githubusercontent.com/81623053/116964348-97bc0980-acab-11eb-925b-0941823748b1.png)

Here is my configuration in /etc/dhcpcd.conf:
![image](https://user-images.githubusercontent.com/81623053/116965427-0f8b3380-acae-11eb-8e99-ff940f553a3f.png)

Best regards
Gaetan

**Comment by Gaetanos-99** [comment]
I had to connect my Raspi to the other Raspi with an Ethernet cable and it worked. I also had to define eth0 ip adresses of both Raspis in another range. Now it's functionning.

Best regards
Gaetan
