### ISSUE TITLE
how to add second api 

### ISSUE THREAD

**Issue by yaterya** [rtlabs-com/p-net#438]
I want to implement for 2 api profinet , I modify API_MAX to 2 
and add my module and submodule in app_gsdml.h, 
but it doesn't work, 

Module plug indication
  Pull old module.    API: 19969 Slot:  1
  Plug module.        API: 19969 Slot:  1 Module ID: 0x30 DI 8xLogicLevel
Submodule plug indication.
  Pull old submodule. API: 19969 Slot:  1 Subslot: 1
  Plug submodule.     API: 19969 Slot:  1 Module ID: 0x30
                      Subslot: 1 Submodule ID: 0x130 "Digital Input"
                      Data Dir: INPUT In: 1 Out: 0
Submodule plug indication.
  Pull old submodule. API: 19969 Slot:  1 Subslot: 2
  Plug submodule.     API: 19969 Slot:  1 Module ID: 0x30
                      Subslot: 2 Submodule ID: 0x1011 "sub2"
                      Data Dir: INPUT_OUTPUT In: 17 Out: 16
p_iocr_param->nbr_apis = 2
api_id = 19969
Event indication PNET_EVENT_ABORT   AREP: 1
    Error class: 0x00 Not decoded
    Error code:  0x00 Not decoded
Setting outputs to default values.
Connection closed
Waiting for PLC connect request

does p-net support add second api?

thanks

**Comment by JanVasina** [comment]
I don't know if it would solve your problem, but try the change I have described in issuse #440.
I went to the similar problem as you when trying to implement the second PROFIdrive API (0x3A00).

**Comment by pyhys** [comment]
We have now merged #449. Please reopen if the problem persists.
