### ISSUE TITLE
GSD FILE 

### ISSUE THREAD

**Issue by Tahe97** [rtlabs-com/p-net#478]
Good afternoon , 
i tried to use the gsd file in this project to configure communication between RPI 4 and s7 1500 .after configuration s7 doesn't reconized RPI as a device . 
any advices ?

**Comment by pyhys** [comment]
You can use Proneta to scan the network for Profinet devices. Verify that your (RPI-based) IO-device show up there. 
I would recommend that as the first step. 
See https://rt-labs.com/docs/p-net/network_topology_detection.html#siemens-proneta-profinet-network-analysis-tool

**Comment by Tahe97** [comment]
I tried to install Protena on RPI but i think that i have a problem in the connection WIFI so i tried to install Protena on windows but also he doesn't reconized it it shows only plc .
for the hardware : i use the two ports ethernet of the plc one for the pc and one for the raspberry 
sorry for dump question but i m new in automatisme and i m gratefull for you help

**Comment by pyhys** [comment]
Try to follow the tutorial as close as possible, and run with DEBUG log level. Paste the printout from the sample app here, and I will try to help you.

**Comment by Tahe97** [comment]
good morning 
i tried to folow the tuto but i have such commands don work this is what i have .
for the lldp it is working good 
`lldpcli show neighbors 
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------
Interface:    eth0, via: LLDP, RID: 9, Time: 0 day, 00:00:07
  Chassis:     
    ChassisID:    local S7-1500                   6ES7 513-1AL02-0AB0  S C-K5PE09262018     1 V  2  5  0
    SysDescr:     Siemens, SIMATIC S7, CPU 1513-1 PN, 6ES7 513-1AL02-0AB0, HW: Version 1, FW: Version V2.5.0, S C-K5PE09262018
    MgmtIP:       192.168.0.1
    Capability:   Bridge, on
    Capability:   Station, on
  Port:        
    PortID:       local port-002.plcxb2d1ad
    PortDescr:    Siemens, SIMATIC S7, Ethernet Port, X1 P2R
    TTL:          20
  Unknown TLVs:
    TLV:          OUI: 00,0E,CF, SubType: 1, Len: 20 00,00,01,39,00,00,00,00,00,00,00,29,00,00,00,00,00,00,00,00
    TLV:          OUI: 00,0E,CF, SubType: 2, Len: 4 00,00,00,00
    TLV:          OUI: 00,0E,CF, SubType: 5, Len: 6 AC,64,17,13,FB,59
-------------------------------------------------------------------------------
Interface:    wlan0, via: LLDP, RID: 8, Time: 0 day, 00:27:18
  Chassis:     
    ChassisID:    local jackie
    SysName:      JACKIE
    SysDescr:     Micro-Star International Co., Ltd. GF63 Thin 9RCX,REV:1.0,9S716R312678ZJ8000115 + HMI
    MgmtIP:       192.168.137.1
    Capability:   Station, on
  Port:        
    PortID:       local port-001
    TTL:          20
  Unknown TLVs:
    TLV:          OUI: 00,0E,CF, SubType: 2, Len: 4 00,00,00,00
    TLV:          OUI: 00,0E,CF, SubType: 5, Len: 6 0E,DD,24,A7,89,65
-------------------------------------------------------------------------------`
but for the snmp i have a problem with the version v2c
`snmpwalk -v2c -c public 192.168.0.1
Timeout: No Response from 192.168.0.1`
but it'is working with v1
`snmpwalk -v1 -c public 192.168.0.1
iso.3.6.1.2.1.1.1.0 = STRING: "Siemens, SIMATIC S7, CPU 1513-1 PN, 6ES7 513-1AL02-0AB0, HW: Version 1, FW: Version V2.5.0, S C-K5PE09262018"
iso.3.6.1.2.1.1.2.0 = OID: ccitt.0
iso.3.6.1.2.1.1.3.0 = Timeticks: (606910) 1:41:09.10
iso.3.6.1.2.1.1.4.0 = ""
iso.3.6.1.2.1.1.5.0 = ""
iso.3.6.1.2.1.1.6.0 = ""
iso.3.6.1.2.1.1.7.0 = INTEGER: 78
iso.3.6.1.2.1.1.8.0 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.1.9.1.2.1 = OID: iso.0.8802.1.1.2
iso.3.6.1.2.1.1.9.1.2.2 = OID: iso.0.62439.1
iso.3.6.1.2.1.1.9.1.2.3 = OID: iso.3.6.1.2.1
iso.3.6.1.2.1.1.9.1.2.4 = OID: iso.3.6.1.2.1.4
iso.3.6.1.2.1.1.9.1.2.5 = OID: iso.3.6.1.2.1.5
iso.3.6.1.2.1.1.9.1.2.6 = OID: iso.3.6.1.2.1.6
iso.3.6.1.2.1.1.9.1.2.7 = OID: iso.3.6.1.2.1.7
iso.3.6.1.2.1.1.9.1.2.8 = OID: iso.3.6.1.2.1.11
iso.3.6.1.2.1.1.9.1.2.9 = OID: iso.3.6.1.2.1.31
iso.3.6.1.2.1.1.9.1.3.1 = STRING: "iso.0.iso8802.ieee802dot1.ieee802dot1mibs.lldp"
iso.3.6.1.2.1.1.9.1.3.2 = STRING: "iso.0.iec62439.mrp"
iso.3.6.1.2.1.1.9.1.3.3 = STRING: "iso.org.dod.internet.mgmt.mib_2"
iso.3.6.1.2.1.1.9.1.3.4 = STRING: "iso.org.dod.internet.mgmt.mib_2.ipMIB"
iso.3.6.1.2.1.1.9.1.3.5 = STRING: "iso.org.dod.internet.mgmt.mib_2.icmpMIB"
iso.3.6.1.2.1.1.9.1.3.6 = STRING: "iso.org.dod.internet.mgmt.mib_2.tcpMIB"
iso.3.6.1.2.1.1.9.1.3.7 = STRING: "iso.org.dod.internet.mgmt.mib_2.udpMIB"
iso.3.6.1.2.1.1.9.1.3.8 = STRING: "iso.org.dod.internet.mgmt.mib_2.snmp"
iso.3.6.1.2.1.1.9.1.3.9 = STRING: "iso.org.dod.internet.mgmt.mib_2.ifMIB"
iso.3.6.1.2.1.1.9.1.4.1 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.1.9.1.4.2 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.1.9.1.4.3 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.1.9.1.4.4 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.1.9.1.4.5 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.1.9.1.4.6 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.1.9.1.4.7 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.1.9.1.4.8 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.1.9.1.4.9 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.2.1.0 = INTEGER: 3
iso.3.6.1.2.1.2.2.1.1.1 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.1.2 = INTEGER: 2
iso.3.6.1.2.1.2.2.1.1.3 = INTEGER: 3
iso.3.6.1.2.1.2.2.1.2.1 = STRING: "Siemens, SIMATIC S7, internal, X1"
iso.3.6.1.2.1.2.2.1.2.2 = STRING: "Siemens, SIMATIC S7, Ethernet Port, X1 P1R"
iso.3.6.1.2.1.2.2.1.2.3 = STRING: "Siemens, SIMATIC S7, Ethernet Port, X1 P2R"
iso.3.6.1.2.1.2.2.1.3.1 = INTEGER: 6
iso.3.6.1.2.1.2.2.1.3.2 = INTEGER: 6
iso.3.6.1.2.1.2.2.1.3.3 = INTEGER: 6
iso.3.6.1.2.1.2.2.1.4.1 = INTEGER: 1500
iso.3.6.1.2.1.2.2.1.4.2 = INTEGER: 1500
iso.3.6.1.2.1.2.2.1.4.3 = INTEGER: 1500
iso.3.6.1.2.1.2.2.1.5.1 = Gauge32: 100000000
iso.3.6.1.2.1.2.2.1.5.2 = Gauge32: 100000000
iso.3.6.1.2.1.2.2.1.5.3 = Gauge32: 100000000
iso.3.6.1.2.1.2.2.1.6.1 = Hex-STRING: AC 64 17 13 FB 59 
iso.3.6.1.2.1.2.2.1.6.2 = Hex-STRING: AC 64 17 13 FB 5A 
iso.3.6.1.2.1.2.2.1.6.3 = Hex-STRING: AC 64 17 13 FB 5B 
iso.3.6.1.2.1.2.2.1.7.1 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.7.2 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.7.3 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.8.1 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.8.2 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.8.3 = INTEGER: 1
iso.3.6.1.2.1.2.2.1.9.1 = Timeticks: (100) 0:00:01.00
iso.3.6.1.2.1.2.2.1.9.2 = Timeticks: (508930) 1:24:49.30
iso.3.6.1.2.1.2.2.1.9.3 = Timeticks: (594950) 1:39:09.50
iso.3.6.1.2.1.2.2.1.10.2 = Counter32: 374303
iso.3.6.1.2.1.2.2.1.10.3 = Counter32: 298196
iso.3.6.1.2.1.2.2.1.11.1 = Counter32: 3864
iso.3.6.1.2.1.2.2.1.11.2 = Counter32: 61
iso.3.6.1.2.1.2.2.1.11.3 = Counter32: 2887
iso.3.6.1.2.1.2.2.1.12.2 = Counter32: 2138
iso.3.6.1.2.1.2.2.1.12.3 = Counter32: 301
iso.3.6.1.2.1.2.2.1.13.2 = Counter32: 0
iso.3.6.1.2.1.2.2.1.13.3 = Counter32: 0
iso.3.6.1.2.1.2.2.1.14.2 = Counter32: 0
iso.3.6.1.2.1.2.2.1.14.3 = Counter32: 0
iso.3.6.1.2.1.2.2.1.15.2 = Counter32: 1340
iso.3.6.1.2.1.2.2.1.15.3 = Counter32: 91
iso.3.6.1.2.1.2.2.1.16.2 = Counter32: 808964
iso.3.6.1.2.1.2.2.1.16.3 = Counter32: 1086239
iso.3.6.1.2.1.2.2.1.17.1 = Counter32: 13857
iso.3.6.1.2.1.2.2.1.17.2 = Counter32: 68
iso.3.6.1.2.1.2.2.1.17.3 = Counter32: 263
iso.3.6.1.2.1.2.2.1.18.2 = Counter32: 7403
iso.3.6.1.2.1.2.2.1.18.3 = Counter32: 9288
iso.3.6.1.2.1.2.2.1.20.2 = Counter32: 0
iso.3.6.1.2.1.2.2.1.20.3 = Counter32: 0
iso.3.6.1.2.1.2.2.1.22.1 = OID: ccitt.0
iso.3.6.1.2.1.2.2.1.22.2 = OID: ccitt.0
iso.3.6.1.2.1.2.2.1.22.3 = OID: ccitt.0
iso.3.6.1.2.1.4.1.0 = INTEGER: 2
iso.3.6.1.2.1.4.2.0 = INTEGER: 64
iso.3.6.1.2.1.4.3.0 = Counter32: 2878
iso.3.6.1.2.1.4.4.0 = Counter32: 0
iso.3.6.1.2.1.4.5.0 = Counter32: 1350
iso.3.6.1.2.1.4.6.0 = Counter32: 0
iso.3.6.1.2.1.4.7.0 = Counter32: 0
iso.3.6.1.2.1.4.8.0 = Counter32: 0
iso.3.6.1.2.1.4.9.0 = Counter32: 1534
iso.3.6.1.2.1.4.10.0 = Counter32: 123
iso.3.6.1.2.1.4.11.0 = Counter32: 0
iso.3.6.1.2.1.4.12.0 = Counter32: 0
iso.3.6.1.2.1.4.13.0 = INTEGER: 60
iso.3.6.1.2.1.4.14.0 = Counter32: 0
iso.3.6.1.2.1.4.15.0 = Counter32: 0
iso.3.6.1.2.1.4.16.0 = Counter32: 0
iso.3.6.1.2.1.4.17.0 = Counter32: 0
iso.3.6.1.2.1.4.18.0 = Counter32: 0
iso.3.6.1.2.1.4.19.0 = Counter32: 0
iso.3.6.1.2.1.4.20.1.1.192.168.0.1 = IpAddress: 192.168.0.1
iso.3.6.1.2.1.4.20.1.2.192.168.0.1 = INTEGER: 1
iso.3.6.1.2.1.4.20.1.3.192.168.0.1 = IpAddress: 255.255.255.0
iso.3.6.1.2.1.4.20.1.4.192.168.0.1 = INTEGER: 1
iso.3.6.1.2.1.4.20.1.5.192.168.0.1 = INTEGER: 65535
iso.3.6.1.2.1.4.21.1.1.192.168.0.0 = IpAddress: 192.168.0.0
iso.3.6.1.2.1.4.21.1.2.192.168.0.0 = INTEGER: 1
iso.3.6.1.2.1.4.21.1.3.192.168.0.0 = INTEGER: -1
iso.3.6.1.2.1.4.21.1.4.192.168.0.0 = INTEGER: -1
iso.3.6.1.2.1.4.21.1.5.192.168.0.0 = INTEGER: -1
iso.3.6.1.2.1.4.21.1.6.192.168.0.0 = INTEGER: -1
iso.3.6.1.2.1.4.21.1.7.192.168.0.0 = IpAddress: 192.168.0.1
iso.3.6.1.2.1.4.21.1.8.192.168.0.0 = INTEGER: 3
iso.3.6.1.2.1.4.21.1.9.192.168.0.0 = INTEGER: 2
iso.3.6.1.2.1.4.21.1.10.192.168.0.0 = INTEGER: 6068
iso.3.6.1.2.1.4.21.1.11.192.168.0.0 = IpAddress: 255.255.255.0
iso.3.6.1.2.1.4.21.1.12.192.168.0.0 = INTEGER: -1
iso.3.6.1.2.1.4.21.1.13.192.168.0.0 = OID: ccitt.0
iso.3.6.1.2.1.4.22.1.1.1.192.168.0.35 = INTEGER: 1
iso.3.6.1.2.1.4.22.1.2.1.192.168.0.35 = Hex-STRING: DC A6 32 1A 43 B3 
iso.3.6.1.2.1.4.22.1.3.1.192.168.0.35 = IpAddress: 192.168.0.35
iso.3.6.1.2.1.4.22.1.4.1.192.168.0.35 = INTEGER: 3
iso.3.6.1.2.1.4.23.0 = Counter32: 0
iso.3.6.1.2.1.5.1.0 = Counter32: 12
iso.3.6.1.2.1.5.2.0 = Counter32: 0
iso.3.6.1.2.1.5.3.0 = Counter32: 0
iso.3.6.1.2.1.5.4.0 = Counter32: 0
iso.3.6.1.2.1.5.5.0 = Counter32: 0
iso.3.6.1.2.1.5.6.0 = Counter32: 0
iso.3.6.1.2.1.5.7.0 = Counter32: 0
iso.3.6.1.2.1.5.8.0 = Counter32: 12
iso.3.6.1.2.1.5.9.0 = Counter32: 0
iso.3.6.1.2.1.5.10.0 = Counter32: 0
iso.3.6.1.2.1.5.11.0 = Counter32: 0
iso.3.6.1.2.1.5.12.0 = Counter32: 0
iso.3.6.1.2.1.5.13.0 = Counter32: 0
iso.3.6.1.2.1.5.14.0 = Counter32: 1290
iso.3.6.1.2.1.5.15.0 = Counter32: 1278
iso.3.6.1.2.1.5.16.0 = Counter32: 0
iso.3.6.1.2.1.5.17.0 = Counter32: 0
iso.3.6.1.2.1.5.18.0 = Counter32: 0
iso.3.6.1.2.1.5.19.0 = Counter32: 0
iso.3.6.1.2.1.5.20.0 = Counter32: 0
iso.3.6.1.2.1.5.21.0 = Counter32: 0
iso.3.6.1.2.1.5.22.0 = Counter32: 12
iso.3.6.1.2.1.5.23.0 = Counter32: 0
iso.3.6.1.2.1.5.24.0 = Counter32: 0
iso.3.6.1.2.1.5.25.0 = Counter32: 0
iso.3.6.1.2.1.5.26.0 = Counter32: 0
iso.3.6.1.2.1.6.1.0 = INTEGER: 1
iso.3.6.1.2.1.6.2.0 = INTEGER: 1000
iso.3.6.1.2.1.6.3.0 = INTEGER: 128000
iso.3.6.1.2.1.6.4.0 = INTEGER: -1
iso.3.6.1.2.1.6.5.0 = Counter32: 0
iso.3.6.1.2.1.6.6.0 = Counter32: 0
iso.3.6.1.2.1.6.7.0 = Counter32: 0
iso.3.6.1.2.1.6.8.0 = Counter32: 0
iso.3.6.1.2.1.6.9.0 = Gauge32: 0
iso.3.6.1.2.1.6.10.0 = Counter32: 0
iso.3.6.1.2.1.6.11.0 = Counter32: 0
iso.3.6.1.2.1.6.12.0 = Counter32: 0
iso.3.6.1.2.1.6.13.1.1.0.0.0.0.102.0.0.0.0.0 = INTEGER: 2
iso.3.6.1.2.1.6.13.1.2.0.0.0.0.102.0.0.0.0.0 = IpAddress: 0.0.0.0
iso.3.6.1.2.1.6.13.1.3.0.0.0.0.102.0.0.0.0.0 = INTEGER: 102
iso.3.6.1.2.1.6.13.1.4.0.0.0.0.102.0.0.0.0.0 = IpAddress: 0.0.0.0
iso.3.6.1.2.1.6.13.1.5.0.0.0.0.102.0.0.0.0.0 = INTEGER: 0
iso.3.6.1.2.1.6.14.0 = Counter32: 0
iso.3.6.1.2.1.6.15.0 = Counter32: 0
iso.3.6.1.2.1.7.1.0 = Counter32: 1601
iso.3.6.1.2.1.7.2.0 = Counter32: 1401
iso.3.6.1.2.1.7.3.0 = Counter32: 0
iso.3.6.1.2.1.7.4.0 = Counter32: 192
iso.3.6.1.2.1.7.5.1.1.0.0.0.0.161 = IpAddress: 0.0.0.0
iso.3.6.1.2.1.7.5.1.1.0.0.0.0.34964 = IpAddress: 0.0.0.0
iso.3.6.1.2.1.7.5.1.1.0.0.0.0.56140 = IpAddress: 0.0.0.0
iso.3.6.1.2.1.7.5.1.1.0.0.0.0.61899 = IpAddress: 0.0.0.0
iso.3.6.1.2.1.7.5.1.2.0.0.0.0.161 = INTEGER: 161
iso.3.6.1.2.1.7.5.1.2.0.0.0.0.34964 = INTEGER: 34964
iso.3.6.1.2.1.7.5.1.2.0.0.0.0.56140 = INTEGER: 56140
iso.3.6.1.2.1.7.5.1.2.0.0.0.0.61899 = INTEGER: 61899
iso.3.6.1.2.1.11.1.0 = Counter32: 198
iso.3.6.1.2.1.11.2.0 = Counter32: 188
iso.3.6.1.2.1.11.3.0 = Counter32: 10
iso.3.6.1.2.1.11.4.0 = Counter32: 0
iso.3.6.1.2.1.11.5.0 = Counter32: 0
iso.3.6.1.2.1.11.6.0 = Counter32: 0
iso.3.6.1.2.1.11.8.0 = Counter32: 0
iso.3.6.1.2.1.11.9.0 = Counter32: 0
iso.3.6.1.2.1.11.10.0 = Counter32: 0
iso.3.6.1.2.1.11.11.0 = Counter32: 0
iso.3.6.1.2.1.11.12.0 = Counter32: 0
iso.3.6.1.2.1.11.13.0 = Counter32: 199
iso.3.6.1.2.1.11.14.0 = Counter32: 0
iso.3.6.1.2.1.11.15.0 = Counter32: 0
iso.3.6.1.2.1.11.16.0 = Counter32: 202
iso.3.6.1.2.1.11.17.0 = Counter32: 0
iso.3.6.1.2.1.11.18.0 = Counter32: 0
iso.3.6.1.2.1.11.19.0 = Counter32: 0
iso.3.6.1.2.1.11.20.0 = Counter32: 0
iso.3.6.1.2.1.11.21.0 = Counter32: 0
iso.3.6.1.2.1.11.22.0 = Counter32: 0
iso.3.6.1.2.1.11.24.0 = Counter32: 0
iso.3.6.1.2.1.11.25.0 = Counter32: 0
iso.3.6.1.2.1.11.26.0 = Counter32: 0
iso.3.6.1.2.1.11.27.0 = Counter32: 0
iso.3.6.1.2.1.11.28.0 = Counter32: 0
iso.3.6.1.2.1.11.29.0 = Counter32: 0
iso.3.6.1.2.1.11.30.0 = INTEGER: 2
iso.3.6.1.2.1.11.31.0 = Counter32: 0
iso.3.6.1.2.1.11.32.0 = Counter32: 0
End of MIB
`
also i cant do any snmpset 
`snmpset -v1 -c private 192.168.0.1 1.3.6.1.2.1.1.6.0 "My new location"
1.3.6.1.2.1.1.6.0: Bad object type: M
`

**Comment by Tahe97** [comment]
Also to be informed this what i have in the plc it doesn't reconized the raspberry 
![20220325_105245](https://user-images.githubusercontent.com/73806466/160100858-09cde694-3cb7-474e-b0b8-dca1f7cabb8b.jpg)
![20220325_105222](https://user-images.githubusercontent.com/73806466/160100886-142b6da1-5b2d-419c-839e-69d6147409d1.jpg)

**Comment by pyhys** [comment]
Could you please provide a printout from the sample app?

**Comment by Tahe97** [comment]
honestly i didn't understand you verry well and i really nead your healp because i have made many researshs i didn't find any thing helpfull . this is my address mail  you can send me tahe.taamallah97@gmail.com i will expalin to you what i want to do and what i have done . thank you

**Comment by Tahe97** [comment]
it worked very well. i didn't understand you from the first about the sample application . but it's ok thank uou sir
