### ISSUE TITLE
1500PLC超过18个带Recod的slot就无法组态成功，1200PLC超过40个带Record的slot就无法组态成功。

### ISSUE THREAD

**Issue by hangeV** [rtlabs-com/p-net#502]
1500PLC超过18个带Record的slot就无法组态成功，1200PLC超过40个带Record的slot就无法组态成功。

1200PLC超过40个带Record的slot无法组态成功，我通过如下修改解决了。
![image](https://user-images.githubusercontent.com/66555955/171829550-ee3bbc9f-5cb0-4781-b8f2-cc9ff42bd2ac.png)
https://github.com/rtlabs-com/p-net/issues/493

1500PLC超过18个带Record的slot也会无法组态成功，我通过如下解决了。
![image](https://user-images.githubusercontent.com/66555955/171829103-fb405991-adae-4396-bd86-7c5cae29f51b.png)

wireshark抓取1500PLC分别插入10、20、40、50个带Record的slot。
[wireshark.zip](https://github.com/rtlabs-com/p-net/files/8821170/wireshark.zip)
通过wireshark抓包发现：1500PLC"write request"是“little endian”，两包(当超过18个带Record的slot会分包)都是"little endian"。而p-net"write response"时第一包是"big endian"，而第二包是"little endian"。所以组态失败。
![image](https://user-images.githubusercontent.com/66555955/171804275-4f4cebe2-e0e0-4718-bb90-6d57f23267c2.png)

而不分包的情况下1500PLC"write request"是“little endian”，p-net"write response"是"big endian"可以组态成功。

**Comment by hangeV** [comment]
通过wireshark抓包发现：1500PLC"write request"是“little endian”，两包(当超过18个带Record的slot会分包)都是"little endian"。而p-net"write response"时第一包是"big endian"，而第二包是"little endian"。所以组态失败。

**Comment by pyhys** [comment]
Please provide an english translation.
