### ISSUE TITLE
Is it possible to use ubuntu + p-net to control a SIEMENS V90(PN) servo?

### ISSUE THREAD

**Issue by wei1224hf** [rtlabs-com/p-net#508]
I have a PC , running Ubuntu 20.04, 
A SIEMENS V90 servo controller and a SIEMENS S1-F16 servo motor, they are connected, 
is it possible to control the SIEMENS servo with p-net ?
I can control a servo motor by EtherCAT-igh , so I wan't to control a profinet servo by p-net , 
but after reading some documents , there is no such example

**Comment by pyhys** [comment]
The p-net stack is a Profinet IO-device, but you need an IO-controller (PLC) to control your servo.
P-net can unfortunately not do that.

**Comment by wei1224hf** [comment]
@pyhys  Thanks
