### ISSUE TITLE
Sending Profinet data between two computers

### ISSUE THREAD

**Issue by soland1** [rtlabs-com/p-net#518]
I'm looking for a way to send and receive Profinet frames between two computers.

Does this device stack provide a way I could write my own Profinet messages and receive them on another computer? My goal would be to avoid the need to have a PLC program running on a Rasberry Pi and I would like to send my own data inside the Profinet frames.

**Comment by pyhys** [comment]
Hi!
Profinet communication must go via an IO-controller (PLC). This stack is an IO-device stack (for connection to a PLC), but is unfortunately not an IO-controller stack.

**Comment by soland1** [comment]
Thank you for the answer.
