### ISSUE TITLE
using on MCU without OS

### ISSUE THREAD

**Issue by Armin234** [rtlabs-com/p-net#524]
Hi,
I'm trying to getting running P_Net on a TI RM46 without any OS, but lwip 1.4.1 is running. Futhermore I know how getting any Ethernet frame Layer 2 und sending Ethernet Frame as well.
Is there any suggestion what I must do ?

**Comment by pyhys** [comment]
Hi!
We use the pnal directory in the repo for some adaption to different hardware, and also uses the separate https://github.com/rtlabs-com/osal repo for some general hardware dependent adaptions.

A good starting point is to look there, and adapt to your hardware.
