### ISSUE TITLE
Sending a bunch of bytes of data to plc

### ISSUE THREAD

**Issue by ai-zml** [rtlabs-com/p-net#543]
How to send more than one byte of data to plc? Like five or ten bytes or more...
Any examples?

**Comment by pyhys** [comment]
Hi, yes there are examples available. See https://rt-labs.com/docs/p-net/codesys_guide.html#using-the-echo-module and https://rt-labs.com/docs/p-net/use_with_siematic.html#using-the-echo-module

**Comment by ai-zml** [comment]
Hi, @pyhys. Thanks for your help. I finally send a bunch of bytes of data. But I got the warning: 
Warning: Failed to connect to the agentx master agent ([NIL]):

I have no idea what it is.
