### ISSUE TITLE
link in readme.md is broken

### ISSUE THREAD

**Issue by bauergeorg** [rtlabs-com/p-net#568]
The link at [README.MD](https://github.com/rtlabs-com/p-net#readme)
> See the tutorial in the documentation: https://rt-labs.com/docs/p-net/tutorial.html

is broken.

**Comment by pyhys** [comment]
You are right. We will update it to https://docs.rt-labs.com/p-net/running_sample_app.html at next release.

**Comment by bauergeorg** [comment]
Is there a possibility to get the documentation without user-login?

The page looks like this:
<img width="320" alt="image" src="https://github.com/rtlabs-com/p-net/assets/79077565/f019462d-89a1-40a2-976b-b5e142664458">

**Comment by elupus** [comment]
No at the moment. The documentation requires a login. The login has no cost ascociated thou.
