### ISSUE TITLE
The smart200 plc cannot be connected

### ISSUE THREAD

**Issue by tomyqg** [rtlabs-com/p-net#584]
I run p-net sampleapp on nuvoTon nuc980 platform with rtos and lwip,
However, the smart200 plc cannot be connected properly.
The following debugging information is obtained:

 \ | /
- RT -     Thread Operating System
 / | \     5.0.0 build May 18 2024 18:28:46
 2006 - 2022 Copyright by RT-Thread team
lwIP-2.1.2 initialized!
[32m[I/I2C] I2C bus [i2c1] registered[0m
[32m[I/SFUD] Find a Winbond flash chip. Size is 16777216 bytes.[0m
[32m[I/SFUD] norflash0 flash device is initialize success.[0m
[32m[I/SFUD] Probe SPI flash norflash0 by SPI device qspi01 success.[0m
[32m[I/sal.skt] Socket Abstraction Layer initialize success.[0m
[D/FAL] (fal_flash_init:47) Flash device |                norflash0 | addr: 0x00000000 | len: 0x01000000 | blk_size: 0x00001000 |initialized finish.
[32;22m[I/FAL] ==================== FAL partition table ====================[0m
[32;22m[I/FAL] | name     | flash_dev |   offset   |    length  |[0m
[32;22m[I/FAL] -------------------------------------------------------------[0m
[32;22m[I/FAL] | rtthread | norflash0 | 0x00000000 | 0x00400000 |[0m
[32;22m[I/FAL] | fat      | norflash0 | 0x00400000 | 0x00800000 |[0m
[32;22m[I/FAL] | llfs     | norflash0 | 0x00c00000 | 0x00200000 |[0m
[32;22m[I/FAL] | kvdb     | norflash0 | 0x00e00000 | 0x00200000 |[0m
[32;22m[I/FAL] =============================================================[0m
[32;22m[I/FAL] RT-Thread Flash Abstraction Layer initialize success.[0m
[32;22m[I/FAL] The FAL block device (fat) created successfully[0m
[PDMA-W]
[32;22m[I/FAL] The FAL MTD NOR device (llfs) created successfully[0m
lfs_mount3222 
MAC address: 82:06:21:53:94:54
API(107): Application calls pnet_init()
msh />FILE(181): Did read file /flash/pnet_data_im.bin Access time 3 ms.
FSPM(304): Did read I&M settings from nvm.
FILE(181): Did read file /flash/pnet_data_im.bin Access time 2 ms.
FSPM(360): No storing of nvm I&M settings (no changes).
FSPM(1409): Triggering signal LED callback with state 0.
CPM(81): Init driver
CPM_DRIVER_SW(543): Default CPM driver installed
PPM(51): Init driver
PPM_DRIVER_SW(289): Default PPM driver installed
ETH(78): Initialising interface "e0" 82:06:21:53:94:54 Ethertype 0xFFFF
CMINA(174): Setting default configuration. Reset mode: 0
FILE(181): Did read file /flash/pnet_data_ip.bin Access time 2 ms.
CMINA(209): Did read IP parameters from nvm
CMINA(268): Using IP: 192.168.2.23 Netmask: 255.255.255.0 Gateway: 192.168.2.1 Station name: "rt-labs-dev"
CMINA(547): Start senFILE(181): Did read file /flash/pnet_data_ip.bin Access time 2 ms.
CMINA(139): No storing of nvm IP settings (no changes). IP: 192.168.2.23 Netmask: 255.255.255.0 Gateway: 192.168.2.1 Station name: "rt-labs-dev"
d255.255.0 Gateway: 192CMINA(421): Setting IP: 192.168.2.23 Netmask: 255.255.255.0 Gateway: 192.168.2.1 Station name: "rt-labs-dev" Permanent: 1
DCP(2016): Activate. Register frame handlers.
ETH(282): Framehandler is adding FrameId 0xfefc at index 0.
ETH(282): Framehandler is adding FrameId 0xfefd at index 1.
ETH(282): Framehandler is adding FrameId 0xfefe at index 2.
FILE(181): Did read file /flash/pnet_data_pdport_1.bin Access time 2 ms.
PDPORT(120): Did read PDPort settings from nvm. No monitoring of peer on port 1.
LLDP(1172): Enabling LLDP transmission for port 1
LLDP(1006): Send port 1 MAC: 82:06:21:53:94:54 IP: 192.168.2.23 Chassis ID: "P-Net Sample Application  12345 Abcdefghijk    007                  3 V  0  2  0" Port ID: "port-001.rt-labs-dev"
CMDEV(884): No module in slot 0
CMDEV(660): No submodule in api_id 0 slot 0 subslot 1
CMDEV(842): Plugged submodule ident 0x00000001 number in api 0 slot 0 subslot 1
CMDEV(660): No submodule in api_id 0 slot 0 subslot 32768
CMDEV(842): Plugged submodule ident 0x00008000 number in api 0 slot 0 subslot 32768
CMDEV(660): No submodule in api_id 0 slot 0 subslot 32769
CMDEV(842): Plugged submodule ident 0x00008001 number in api 0 slot 0 subslot 32769
DCP(1271): Sending DCP Hello request. Station name: rt-labs-dev
PDPORT(1016): Link went up on port 1.
[e0] Link status: 100F
CMRPC(5115): Received 80 bytes UDP payload from remote 192.168.2.13:49153, on socket 3 for incoming DCE RPC requests.
CMRPC(4322): Incoming RPC frame. Seq: 0, Serial: 1, Frag num: 0, Frag Len: 0 Fragment flag: "Not set" Last Fragment flag: "Not set", No fack: "Not set"
CMRPC(539): Allocated session 0
CMRPC(4533): Incoming DCE RPC ping on UDP
CMRPC(981): Sending 80 bytes on socket 5 to 192.168.2.13:49153 Payload:"PING response" Session from me:0 Session index:0
CMRPC(5086): Kill session
CMRPC(578): Released session 0
CMRPC(5115): Received 565 bytes UDP payload from remote 192.168.2.13:49153, on socket 3 for incoming DCE RPC requests.
CMRPC(4322): Incoming RPC frame. Seq: 0, Serial: 2, Frag num: 0, Frag Len: 58625 Fragment flag: "Not set" Last Fragment flag: "Not set", No fack: "Not set"
CMRPC(539): Allocated session 0
CMRPC(4367): RPC fragment too large (58625 bytes). Check the conformance of the controller (PLC).
CMRPC(981): Sending 84 bytes on socket 5 to 192.168.2.13:49153 Payload:"REJECT" Session from me:0 Session index:0
CMRPC(5086): Kill session
CMRPC(578): Released session 0
DCP(1271): Sending DCP Hello request. Station name: rt-labs-dev
BR(80): End of buffer reached when looking for a byte
LLDP(1740): Received LLDP frame, but failed to parse it.
DCP(1947): Responding to incoming DCP identify request. All: 0 StationName: rt-labs-dev Alias:   Delay 0 us. Xid: 16843179
DCP(189): Sent a DCP identify response.
LLDP(1006): Send port 1 MAC: 82:06:21:53:94:54 IP: 192.168.2.23 Chassis ID: "P-Net Sample Application  12345 Abcdefghijk    007                  3 V  0  2  0" Port ID: "port-001.rt-labs-dev"
LLDP(2009): Non-profinet LLDP frame received on port 1 Len: 193
LLDP(498): Port 1, receive timeout expired
PDPORT(976): We do not check peer name or portID, so no port-change diagnosis is triggered.
DCP(1271): Sending DCP Hello request. Station name: rt-labs-dev
CMRPC(5115): Received 565 bytes UDP payload from remote 192.168.2.13:49153, on socket 3 for incoming DCE RPC requests.
CMRPC(4322): Incoming RPC frame. Seq: 0, Serial: 0, Frag num: 0, Frag Len: 58625 Fragment flag: "Not set" Last Fragment flag: "Not set", No fack: "Not set"
CMRPC(539): Allocated session 0
CMRPC(4367): RPC fragment too large (58625 bytes). Check the conformance of the controller (PLC).
CMRPC(981): Sending 84 bytes on socket 5 to 192.168.2.13:49153 Payload:"REJECT" Session from me:0 Session index:0
CMRPC(5086): Kill session
CMRPC(578): Released session 0

![cap](https://github.com/rtlabs-com/p-net/assets/9368645/79325e03-e975-401e-81dc-0d9ccf6abc64)

Can anyone tell me where the mistake is? 

Thank you very much!

**Comment by kurisaW** [comment]
@tomyqg 你好前辈，能否向您简单请教一些问题，不会耽误您太多时间的，如果方便的话可以加我微信：Will_ins
