### ISSUE TITLE
Issue : Station 'rt-labs-dev' : 81813F02-PBNIO: DCP no RealStationName

### ISSUE THREAD

**Issue by Rayapati1203** [rtlabs-com/p-net#61]
Hi 

I am facing an issue - the device is not discoverable. and i am getting this error.
"Station 'rt-labs-dev' : 81813F02-PBNIO: DCP no RealStationName"

Setup Environment: 
1. Rsapberry pi as PLC with codesys runtime package running.
2. Codesys development
3. p-net stack with sample app is running under VN ubuntu 18.04 LTS

I have captured the issue snap shots for the reference.
1. Codesys service status (on Raspberry pi system)
![raspberryPI_as_plc_codesys_service_statis](https://user-images.githubusercontent.com/55705864/80931836-022d2780-8d82-11ea-8235-c962b0e96f51.png)

2. Raspberrypi Tab : systemInfo capture text:
[Raspberrypi_tab_systemInfo.txt](https://github.com/rtlabs-com/p-net/files/4572515/Raspberrypi_tab_systemInfo.txt)

3. No real Station Capture:
![norealStation Name](https://user-images.githubusercontent.com/55705864/80931856-1a9d4200-8d82-11ea-9ac2-724bae393b3b.png)

Earlier it was working and i saw all the network traffic including power-up sequence and cyclic data traffic ..In last week suddenly it started giving this issue. I am not able to understand where was the issue. Do you have any input on this issue?
Note: I have re-imaged the raspberry pi , but still it did not help.

Regards
Rayapati

**Comment by Rayapati1203** [comment]
i found the issue ..My environment is setup all ip addresses for Raspberry pi and virtual box ubuntu linux (device IO) on wifi. The Gateway is different in both raspberry pi and linux environment are different. And Then i changed the ip of raspberry pi and linux to static . Then it started working.
I am closing this thread.

**Comment by pyhys** [comment]
Great, thanks for the update!

**Comment by ppcolo** [comment]
> 我发现了问题..我的环境是在 wifi 上为 Raspberry pi 和虚拟盒子 ubuntu linux（设备 IO）设置所有 IP 地址。网关在树莓派和 linux 环境中是不同的。然后我把树莓派和linux的ip改成了静态的。然后它开始工作。我正在关闭这个线程。

我想问下如何设置树莓派的静态ip地址 这个对我来说有点麻烦
