### ISSUE TITLE
Does not check validity of incoming stationname

### ISSUE THREAD

**Issue by pyhys** [rtlabs-com/p-net#77]
Found with Automated RT Tester DCP_3

**Comment by pyhys** [comment]
See discussion in #51

**Comment by pyhys** [comment]
Use skeleton in #96

**Comment by atomic-3dpenguin** [comment]
This fix always reports PF_DCP_BLOCK_ERROR_SUBOPTION_NOT_SET.  To resolve this issue I had to modify the code in pf_cmina.c (attached).
![pnet_name_change_update](https://user-images.githubusercontent.com/66037099/84449031-1aa22480-ac01-11ea-9caf-4591773ec238.png)

**Comment by olbjo** [comment]
Thanks, I added the "else" part. Current status:
![image](https://user-images.githubusercontent.com/58302773/84746598-81835d00-afb6-11ea-82ae-f864b8aae7f1.png)
