### ISSUE TITLE
Protocol violation during IODWrite Request with a single Block

### ISSUE THREAD

**Issue by Svenson12** [rtlabs-com/p-net#8]
When establishing a connection, one of the necessary steps is to handle Write Requests. When these requests are done as Multiple Write, everything seems to work fine.
But when such a write request has just one block, the communication fails.
Reason is, that the response contains the right data, but the trasnmitted data length is 0.

Reason for this issue seems to be the last parameter in line 1897 (pf_cmrpc.c). Currently a pointer to the starting position of the response (&res_start_pos) is used which does not make sense. When using p_res_pos instead (simmilar to the multi-write branch), everything seems to work fine...

https://github.com/rtlabs-com/p-net/blob/6ebfff190484a6f61a867f3c757a267b0e63d805/src/device/pf_cmrpc.c#L1897

Can you confirm?

**Comment by pyhys** [comment]
Yes, I can confirm this. Thanks for the detailed bug report! See PR #30
