### ISSUE TITLE
Errors in DIFFERENT_ACCESS_WAYS test case

### ISSUE THREAD

**Issue by pyhys** [rtlabs-com/p-net#82]
Found with Automated RT Tester DIFFERENT_ACCESS_WAYS

**Comment by pyhys** [comment]
Get StationName, IP, DeviceID. Set StationName temporary, IP temporary. Startup.
Read and Read implicit.
"RecordData length not valid" "Status not valid" etc

**Comment by olbjo** [comment]
First issue I encounter is that the fspm_log_book is not initialized. Initializing net-struct to 0 in pnet_init() resolves this but implementation of pdevdata index seems missing which means the test still fails.

**Comment by pyhys** [comment]
The test case is still not passing. Reopening.
