### ISSUE TITLE
Invalid definition of VLAN priority tags

### ISSUE THREAD

**Issue by Svenson12** [rtlabs-com/p-net#9]
It seems that the definition of the VLAN priotity tags in pf_alarm.c is invalid.
The used shift goes into the wrong direction (should be << instaed >>).
https://github.com/rtlabs-com/p-net/blob/6ebfff190484a6f61a867f3c757a267b0e63d805/src/common/pf_alarm.c#L33-L34

**Comment by pyhys** [comment]
Yes, this is the two-byte TCI field of Ethernet VLAN tags (the priority). See https://en.wikipedia.org/wiki/IEEE_802.1Q
I will fix this.
